version: 2

sources:
  - name: rawdata
    schema: rawdata
    tables:
      - name: order_products__prior
      - name: order_products__train
      - name: orders
      - name: products

models:
  - name: order_products
    columns:
      - name: order_id
        description: "The primary key for order products"
        tests:
          - not_null